# Generated by Django 4.0.2 on 2022-03-03 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_auto_20151126_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='is_employee',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='organisation_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
